# Generated by Django 2.2.1 on 2019-05-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertismentinfo',
            name='GameOrientation',
        ),
        migrations.RemoveField(
            model_name='advertismentinfo',
            name='GamePlatform',
        ),
    ]
