# Generated by Django 2.2.1 on 2019-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisments', '0002_auto_20190525_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertismentinfo',
            name='GameUrl',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='advertismentinfo',
            name='ImageUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
