# Generated by Django 2.2.1 on 2019-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisments', '0003_auto_20190525_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertismentinfo',
            name='GameTitle',
            field=models.CharField(max_length=100),
        ),
    ]
